package verity.ui;

import java.time.LocalDate;
import java.util.List;
import java.util.Scanner;

import verity.task.Task;
import verity.task.TaskList;

/**
 * Handles user input and formats user-facing responses.
 */
public class Ui {
    private static final String HORIZONTAL_LINE =
            "____________________________________________________________\n";

    private final Scanner scanner;

    /**
     * Creates a UI that reads from standard input.
     */
    public Ui() {
        this.scanner = new Scanner(System.in);
    }

    /**
     * Reads the next command entered by the user.
     *
     * @return User command.
     */
    public String readCommand() {
        return scanner.nextLine();
    }

    /**
     * Returns the startup greeting.
     *
     * @return Startup greeting.
     */
    public String getGreeting() {
        // This ASCII art for VERITY was generated by Codex Luna High.
        String banner =
                "V   V  EEEEE  RRRR   IIIII  TTTTT  Y   Y\n"
                        + "V   V  E      R   R    I      T     Y Y\n"
                        + " V V   EEEE   RRRR     I      T      Y\n"
                        + "  V    E      R R      I      T      Y\n"
                        + "  V    EEEEE  R  RR  IIIII    T      Y";

        return HORIZONTAL_LINE
                + banner + "\n\n"
                + "Hello! I'm Verity.\n"
                + "I speak only the truth.\n"
                + "What can I do for you?\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the exit message.
     *
     * @return Exit message.
     */
    public String getExitMessage() {
        return HORIZONTAL_LINE
                + "    Bye. Hope to see you again soon!\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the response for an added task.
     *
     * @param task Added task.
     * @param taskCount Number of tasks after the addition.
     * @return Task-added response.
     */
    public String getTaskAddedMessage(Task task, int taskCount) {
        return HORIZONTAL_LINE
                + "     Got it. I've added this task:\n"
                + "       " + task.getStatus() + "\n"
                + "     Now you have " + taskCount
                + " tasks in the list.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the response for a completed task.
     *
     * @param task Updated task.
     * @return Task-marked response.
     */
    public String getTaskMarkedMessage(Task task) {
        return HORIZONTAL_LINE
                + "\n"
                + "Nice! I've marked this task as done:\n\n"
                + task.getStatus() + "\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the response for a task marked as incomplete.
     *
     * @param task Updated task.
     * @return Task-unmarked response.
     */
    public String getTaskUnmarkedMessage(Task task) {
        return HORIZONTAL_LINE
                + "\n"
                + "Ok, I've marked this task as not done yet:\n\n"
                + task.getStatus() + "\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the response for a deleted task.
     *
     * @param task Deleted task.
     * @param taskCount Number of tasks after deletion.
     * @return Task-deleted response.
     */
    public String getTaskDeletedMessage(Task task, int taskCount) {
        return HORIZONTAL_LINE
                + "\n"
                + "Noted. I've removed this task:\n\n"
                + task.getStatus() + "\n"
                + HORIZONTAL_LINE + "\n"
                + "Now you have " + taskCount
                + " tasks in the list.\n\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns a formatted list of all tasks.
     *
     * @param taskList Task list to format.
     * @return Formatted task-list response.
     */
    public String getTaskListMessage(TaskList taskList) {
        StringBuilder response = new StringBuilder(HORIZONTAL_LINE)
                .append("\n")
                .append("    Here are the tasks in your list:\n\n");

        for (int i = 0; i < taskList.size(); i++) {
            response.append("    ")
                    .append(i + 1)
                    .append(".")
                    .append(taskList.get(i).getStatus())
                    .append("\n");
        }

        return response.append(HORIZONTAL_LINE).toString();
    }

    /**
     * Returns tasks occurring on the specified date.
     *
     * @param date Searched date.
     * @param matchingTasks Tasks occurring on the date.
     * @return Formatted date-search response.
     */
    public String getTasksOnMessage(
            LocalDate date, List<Task> matchingTasks) {
        StringBuilder response = new StringBuilder(HORIZONTAL_LINE)
                .append("\n")
                .append("    Tasks on ")
                .append(date)
                .append(":\n\n");

        for (Task task : matchingTasks) {
            response.append("    ")
                    .append(task.getStatus())
                    .append("\n");
        }

        if (matchingTasks.isEmpty()) {
            response.append(
                    "    There are no tasks on this date.\n");
        }

        return response.append(HORIZONTAL_LINE).toString();
    }

    /**
     * Returns tasks matching a search keyword.
     *
     * @param matchingTasks Tasks matching the keyword.
     * @return Formatted keyword-search response.
     */
    public String getMatchingTasksMessage(
            List<Task> matchingTasks) {
        StringBuilder response = new StringBuilder(HORIZONTAL_LINE)
                .append("\n")
                .append("    Here are the matching tasks "
                        + "in your list:\n\n");

        for (int i = 0; i < matchingTasks.size(); i++) {
            response.append("    ")
                    .append(i + 1)
                    .append(".")
                    .append(matchingTasks.get(i).getStatus())
                    .append("\n");
        }

        if (matchingTasks.isEmpty()) {
            response.append(
                    "    There are no matching tasks.\n");
        }

        return response.append(HORIZONTAL_LINE).toString();
    }

    /**
     * Returns an invalid-command response.
     *
     * @param message Error message.
     * @return Formatted command-error response.
     */
    public String getCommandErrorMessage(String message) {
        return HORIZONTAL_LINE
                + "     Speak your truth. " + message + "\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the loading-error response.
     *
     * @return Formatted loading-error response.
     */
    public String getLoadingErrorMessage() {
        return HORIZONTAL_LINE
                + "     I could not load your saved tasks.\n"
                + "     Please check the data file and try again.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns a response for corrupted saved data.
     *
     * @param message Description of the corrupted data.
     * @return Formatted corrupted-data response.
     */
    public String getCorruptedDataErrorMessage(String message) {
        return HORIZONTAL_LINE
                + "     The saved task data is corrupted.\n"
                + "     " + message + "\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the saving-error response.
     *
     * @return Formatted saving-error response.
     */
    public String getSavingErrorMessage() {
        return HORIZONTAL_LINE
                + "     I could not save your tasks.\n"
                + "     Please check the data folder and try again.\n"
                + HORIZONTAL_LINE;
    }
}
