package verity.ui;

import java.time.LocalDate;
import java.util.List;
import java.util.Scanner;

import verity.client.Client;
import verity.task.Task;
import verity.task.TaskList;

/**
 * Handles console input and delegates user-facing response formatting.
 */
public class Ui {
    static final String HORIZONTAL_LINE =
            "____________________________________________________________\n";

    private final Scanner scanner;
    private final TaskMessageFormatter taskMessageFormatter;
    private final ClientMessageFormatter clientMessageFormatter;

    /**
     * Creates a UI that reads from standard input.
     */
    public Ui() {
        this.scanner = new Scanner(System.in);
        this.taskMessageFormatter = new TaskMessageFormatter();
        this.clientMessageFormatter = new ClientMessageFormatter();
    }

    /**
     * Reads the next command entered by the user.
     *
     * @return User command.
     */
    public String readCommand() {
        return scanner.nextLine();
    }

    /**
     * Returns the startup greeting.
     *
     * @return Startup greeting.
     */
    public String getGreeting() {
        // This ASCII art for VERITY was generated by Codex Luna High.
        String banner =
                "V   V  EEEEE  RRRR   IIIII  TTTTT  Y   Y\n"
                        + "V   V  E      R   R    I      T     Y Y\n"
                        + " V V   EEEE   RRRR     I      T      Y\n"
                        + "  V    E      R R      I      T      Y\n"
                        + "  V    EEEEE  R  RR  IIIII    T      Y";

        return HORIZONTAL_LINE
                + banner + "\n\n"
                + "Hello! I'm Verity.\n"
                + "I speak only the truth.\n"
                + "What can I do for you?\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the exit message.
     *
     * @return Exit message.
     */
    public String getExitMessage() {
        return HORIZONTAL_LINE
                + "    Bye. Hope to see you again soon!\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the command guide.
     *
     * @return Formatted command guide.
     */
    public String getHelpMessage() {
        return HORIZONTAL_LINE
                + "    Verity command guide\n\n"
                + "    Tasks:\n"
                + "      todo DESCRIPTION [/client CLIENT_ID ...]\n"
                + "      deadline DESCRIPTION /by YYYY-MM-DD"
                + " [/client CLIENT_ID ...]\n"
                + "      event DESCRIPTION /from YYYY-MM-DD /to YYYY-MM-DD"
                + " [/client CLIENT_ID ...]\n"
                + "      list\n"
                + "      mark TASK_NUMBER\n"
                + "      unmark TASK_NUMBER\n"
                + "      delete TASK_NUMBER\n"
                + "      find KEYWORD\n"
                + "      finddate YYYY-MM-DD\n\n"
                + "    Clients:\n"
                + "      client add /name NAME [FIELDS]\n"
                + "      client list\n"
                + "      client view CLIENT_ID\n"
                + "      client find NAME\n"
                + "      client edit CLIENT_ID /FIELD VALUE ...\n"
                + "      client edit CLIENT_ID /clear FIELD ...\n"
                + "      client associate CLIENT_ID /task TASK_NUMBER ...\n"
                + "      client dissociate CLIENT_ID /task TASK_NUMBER ...\n"
                + "      client delete CLIENT_ID [confirm]\n\n"
                + "    General:\n"
                + "      help\n"
                + "      bye\n\n"
                + "    Optional client fields: /phone, /email, /address,\n"
                + "    /company, /notes, and /preferred. Use /clear FIELD\n"
                + "    with client edit to clear an optional field.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the response for an added task.
     *
     * @param task Added task.
     * @param taskCount Number of tasks after the addition.
     * @return Task-added response.
     */
    public String getTaskAddedMessage(Task task, int taskCount) {
        return taskMessageFormatter.getTaskAddedMessage(task, taskCount);
    }

    /**
     * Returns the response for a completed task.
     *
     * @param task Updated task.
     * @return Task-marked response.
     */
    public String getTaskMarkedMessage(Task task) {
        return taskMessageFormatter.getTaskMarkedMessage(task);
    }

    /**
     * Returns the response for a task marked as incomplete.
     *
     * @param task Updated task.
     * @return Task-unmarked response.
     */
    public String getTaskUnmarkedMessage(Task task) {
        return taskMessageFormatter.getTaskUnmarkedMessage(task);
    }

    /**
     * Returns the response for a deleted task.
     *
     * @param task Deleted task.
     * @param taskCount Number of tasks after deletion.
     * @return Task-deleted response.
     */
    public String getTaskDeletedMessage(Task task, int taskCount) {
        return taskMessageFormatter.getTaskDeletedMessage(task, taskCount);
    }

    /**
     * Returns a formatted list of all tasks.
     *
     * @param taskList Task list to format.
     * @return Formatted task-list response.
     */
    public String getTaskListMessage(TaskList taskList) {
        return taskMessageFormatter.getTaskListMessage(taskList);
    }

    /**
     * Returns tasks occurring on the specified date.
     *
     * @param date Searched date.
     * @param matchingTasks Tasks occurring on the date.
     * @return Formatted date-search response.
     */
    public String getTasksOnMessage(LocalDate date, List<Task> matchingTasks) {
        return taskMessageFormatter.getTasksOnMessage(date, matchingTasks);
    }

    /**
     * Returns tasks matching a search keyword.
     *
     * @param matchingTasks Tasks matching the keyword.
     * @return Formatted keyword-search response.
     */
    public String getMatchingTasksMessage(List<Task> matchingTasks) {
        return taskMessageFormatter.getMatchingTasksMessage(matchingTasks);
    }

    /**
     * Returns an invalid-command response.
     *
     * @param message Error message.
     * @return Formatted command-error response.
     */
    public String getCommandErrorMessage(String message) {
        return HORIZONTAL_LINE
                + "     No... no, that is not right. " + message + "\n"
                + "     Stay with me and try again.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the loading-error response.
     *
     * @return Formatted loading-error response.
     */
    public String getLoadingErrorMessage() {
        return HORIZONTAL_LINE
                + "     I could not load your saved tasks.\n"
                + "     Please check the data file and try again.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the client-loading-error response.
     *
     * @return Formatted client-loading-error response.
     */
    public String getClientLoadingErrorMessage() {
        return HORIZONTAL_LINE
                + "     I could not load your saved clients.\n"
                + "     Please check the data file and try again.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns a response for corrupted saved data.
     *
     * @param message Description of the corrupted data.
     * @return Formatted corrupted-data response.
     */
    public String getCorruptedDataErrorMessage(String message) {
        return HORIZONTAL_LINE
                + "     The saved task data is corrupted.\n"
                + "     " + message + "\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the saving-error response.
     *
     * @return Formatted saving-error response.
     */
    public String getSavingErrorMessage() {
        return HORIZONTAL_LINE
                + "     I could not save your tasks.\n"
                + "     Please check the data folder and try again.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns a response for a newly added client.
     *
     * @param client Added client.
     * @return Client-added response.
     */
    public String getClientAddedMessage(Client client) {
        return clientMessageFormatter.getClientAddedMessage(client);
    }

    /**
     * Returns the response for an updated client.
     *
     * @param client Updated client.
     * @return Client-updated response.
     */
    public String getClientUpdatedMessage(Client client) {
        return clientMessageFormatter.getClientUpdatedMessage(client);
    }

    /**
     * Returns all clients in their supplied order.
     *
     * @param clients Clients to display.
     * @return Formatted client-list response.
     */
    public String getClientListMessage(List<Client> clients) {
        return clientMessageFormatter.getClientListMessage(clients);
    }

    /**
     * Returns details for one client and its assigned tasks.
     *
     * @param client Client to display.
     * @param tasks Complete task list.
     * @return Formatted client-details response.
     */
    public String getClientDetailsMessage(Client client, TaskList tasks) {
        return clientMessageFormatter.getClientDetailsMessage(client, tasks);
    }

    /**
     * Returns clients matching a name search.
     *
     * @param clients Matching clients.
     * @return Formatted search response.
     */
    public String getMatchingClientsMessage(List<Client> clients) {
        return clientMessageFormatter.getMatchingClientsMessage(clients);
    }

    /**
     * Returns the response after associating a client with tasks.
     *
     * @param client Associated client.
     * @param tasks Complete task list.
     * @param taskIndexes Associated zero-based task indexes.
     * @return Formatted association response.
     */
    public String getClientAssociatedMessage(Client client, TaskList tasks,
            List<Integer> taskIndexes) {
        return clientMessageFormatter.getClientAssociatedMessage(
                client, tasks, taskIndexes);
    }

    /**
     * Returns the response after dissociating a client from tasks.
     *
     * @param client Dissociated client.
     * @param taskIndexes Dissociated zero-based task indexes.
     * @return Formatted dissociation response.
     */
    public String getClientDissociatedMessage(Client client, List<Integer> taskIndexes) {
        return clientMessageFormatter.getClientDissociatedMessage(client, taskIndexes);
    }

    /**
     * Returns the warning shown before a client is deleted.
     *
     * @param client Client awaiting deletion.
     * @param assignedTaskCount Number of assigned tasks.
     * @return Deletion-warning response.
     */
    public String getClientDeleteWarningMessage(Client client, int assignedTaskCount) {
        return clientMessageFormatter.getClientDeleteWarningMessage(
                client, assignedTaskCount);
    }

    /**
     * Returns the response after a client is deleted.
     *
     * @param client Deleted client.
     * @param affectedTaskCount Number of affected tasks.
     * @return Client-deleted response.
     */
    public String getClientDeletedMessage(Client client, int affectedTaskCount) {
        return clientMessageFormatter.getClientDeletedMessage(client, affectedTaskCount);
    }

    /**
     * Returns a general saving-error response for multi-file changes.
     *
     * @return Formatted saving-error response.
     */
    public String getSavingChangesErrorMessage() {
        return HORIZONTAL_LINE
                + "     I could not save your changes.\n"
                + "     Please check the data folder and try again.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns a response for corrupted client data.
     *
     * @param message Description of the corrupted client data.
     * @return Formatted corrupted-client-data response.
     */
    public String getCorruptedClientDataErrorMessage(String message) {
        return HORIZONTAL_LINE
                + "     The saved client data is corrupted.\n"
                + "     " + message + "\n"
                + HORIZONTAL_LINE;
    }
}
