package verity.ui;

import java.time.LocalDate;
import java.util.List;
import java.util.Scanner;

import verity.client.Client;
import verity.task.Task;
import verity.task.TaskList;

/**
 * Handles user input and formats user-facing responses.
 */
public class Ui {
    private static final String HORIZONTAL_LINE =
            "____________________________________________________________\n";

    private final Scanner scanner;

    /**
     * Creates a UI that reads from standard input.
     */
    public Ui() {
        this.scanner = new Scanner(System.in);
    }

    /**
     * Reads the next command entered by the user.
     *
     * @return User command.
     */
    public String readCommand() {
        return scanner.nextLine();
    }

    /**
     * Returns the startup greeting.
     *
     * @return Startup greeting.
     */
    public String getGreeting() {
        // This ASCII art for VERITY was generated by Codex Luna High.
        String banner =
                "V   V  EEEEE  RRRR   IIIII  TTTTT  Y   Y\n"
                        + "V   V  E      R   R    I      T     Y Y\n"
                        + " V V   EEEE   RRRR     I      T      Y\n"
                        + "  V    E      R R      I      T      Y\n"
                        + "  V    EEEEE  R  RR  IIIII    T      Y";

        return HORIZONTAL_LINE
                + banner + "\n\n"
                + "Hello! I'm Verity.\n"
                + "I speak only the truth.\n"
                + "What can I do for you?\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the exit message.
     *
     * @return Exit message.
     */
    public String getExitMessage() {
        return HORIZONTAL_LINE
                + "    Bye. Hope to see you again soon!\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the response for an added task.
     *
     * @param task Added task.
     * @param taskCount Number of tasks after the addition.
     * @return Task-added response.
     */
    public String getTaskAddedMessage(Task task, int taskCount) {
        return HORIZONTAL_LINE
                + "     Got it. I've added this task:\n"
                + "       " + task.getStatus() + "\n"
                + "     Now you have " + taskCount
                + " tasks in the list.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the response for a completed task.
     *
     * @param task Updated task.
     * @return Task-marked response.
     */
    public String getTaskMarkedMessage(Task task) {
        return HORIZONTAL_LINE
                + "\n"
                + "Nice! I've marked this task as done:\n\n"
                + task.getStatus() + "\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the response for a task marked as incomplete.
     *
     * @param task Updated task.
     * @return Task-unmarked response.
     */
    public String getTaskUnmarkedMessage(Task task) {
        return HORIZONTAL_LINE
                + "\n"
                + "Ok, I've marked this task as not done yet:\n\n"
                + task.getStatus() + "\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the response for a deleted task.
     *
     * @param task Deleted task.
     * @param taskCount Number of tasks after deletion.
     * @return Task-deleted response.
     */
    public String getTaskDeletedMessage(Task task, int taskCount) {
        return HORIZONTAL_LINE
                + "\n"
                + "Noted. I've removed this task:\n\n"
                + task.getStatus() + "\n"
                + HORIZONTAL_LINE + "\n"
                + "Now you have " + taskCount
                + " tasks in the list.\n\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns a formatted list of all tasks.
     *
     * @param taskList Task list to format.
     * @return Formatted task-list response.
     */
    public String getTaskListMessage(TaskList taskList) {
        StringBuilder response = new StringBuilder(HORIZONTAL_LINE)
                .append("\n")
                .append("    Here are the tasks in your list:\n\n");

        for (int i = 0; i < taskList.size(); i++) {
            Task task = taskList.get(i);
            response.append("    ")
                    .append(i + 1)
                    .append(".")
                    .append(task.getStatus())
                    .append("\n");
            appendTaskMetadata(response, task, "        ");
        }

        return response.append(HORIZONTAL_LINE).toString();
    }

    /**
     * Returns tasks occurring on the specified date.
     *
     * @param date Searched date.
     * @param matchingTasks Tasks occurring on the date.
     * @return Formatted date-search response.
     */
    public String getTasksOnMessage(
            LocalDate date, List<Task> matchingTasks) {
        StringBuilder response = new StringBuilder(HORIZONTAL_LINE)
                .append("\n")
                .append("    Tasks on ")
                .append(date)
                .append(":\n\n");

        for (Task task : matchingTasks) {
            response.append("    ")
                    .append(task.getStatus())
                    .append("\n");
            appendTaskMetadata(response, task, "        ");
        }

        if (matchingTasks.isEmpty()) {
            response.append(
                    "    There are no tasks on this date.\n");
        }

        return response.append(HORIZONTAL_LINE).toString();
    }

    /**
     * Returns tasks matching a search keyword.
     *
     * @param matchingTasks Tasks matching the keyword.
     * @return Formatted keyword-search response.
     */
    public String getMatchingTasksMessage(
            List<Task> matchingTasks) {
        StringBuilder response = new StringBuilder(HORIZONTAL_LINE)
                .append("\n")
                .append("    Here are the matching tasks "
                        + "in your list:\n\n");

        for (int i = 0; i < matchingTasks.size(); i++) {
            Task task = matchingTasks.get(i);
            response.append("    ")
                    .append(i + 1)
                    .append(".")
                    .append(task.getStatus())
                    .append("\n");
            appendTaskMetadata(response, task, "        ");
        }

        if (matchingTasks.isEmpty()) {
            response.append(
                    "    There are no matching tasks.\n");
        }

        return response.append(HORIZONTAL_LINE).toString();
    }

    /**
     * Returns an invalid-command response.
     *
     * @param message Error message.
     * @return Formatted command-error response.
     */
    public String getCommandErrorMessage(String message) {
        return HORIZONTAL_LINE
                + "     Speak your truth. " + message + "\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the loading-error response.
     *
     * @return Formatted loading-error response.
     */
    public String getLoadingErrorMessage() {
        return HORIZONTAL_LINE
                + "     I could not load your saved tasks.\n"
                + "     Please check the data file and try again.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns a response for corrupted saved data.
     *
     * @param message Description of the corrupted data.
     * @return Formatted corrupted-data response.
     */
    public String getCorruptedDataErrorMessage(String message) {
        return HORIZONTAL_LINE
                + "     The saved task data is corrupted.\n"
                + "     " + message + "\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the saving-error response.
     *
     * @return Formatted saving-error response.
     */
    public String getSavingErrorMessage() {
        return HORIZONTAL_LINE
                + "     I could not save your tasks.\n"
                + "     Please check the data folder and try again.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the response for a newly added client.
     *
     * @param client Added client.
     * @return Client-added response.
     */
    public String getClientAddedMessage(Client client) {
        StringBuilder response = new StringBuilder(HORIZONTAL_LINE)
                .append("    Client added:\n");
        appendClientDetails(response, client, "    ");
        return response.append(HORIZONTAL_LINE).toString();
    }

    /**
     * Returns the response for an updated client.
     *
     * @param client Updated client.
     * @return Client-updated response.
     */
    public String getClientUpdatedMessage(Client client) {
        StringBuilder response = new StringBuilder(HORIZONTAL_LINE)
                .append("    Client updated:\n");
        appendClientDetails(response, client, "    ");
        return response.append(HORIZONTAL_LINE).toString();
    }

    /**
     * Returns all clients in their supplied order.
     *
     * @param clients Clients to display.
     * @return Formatted client-list response.
     */
    public String getClientListMessage(List<Client> clients) {
        if (clients.isEmpty()) {
            return HORIZONTAL_LINE
                    + "    There are no clients.\n"
                    + HORIZONTAL_LINE;
        }
        return getClientCollectionMessage("    Clients:\n\n", clients);
    }

    /**
     * Returns details for one client and its assigned tasks.
     *
     * @param client Client to display.
     * @param tasks Complete task list.
     * @return Formatted client-details response.
     */
    public String getClientDetailsMessage(Client client, TaskList tasks) {
        StringBuilder response = new StringBuilder(HORIZONTAL_LINE)
                .append("    Client details:\n");
        appendClientDetails(response, client, "    ");
        response.append("\n    Assigned tasks:\n");
        boolean hasAssignedTask = false;
        for (int i = 0; i < tasks.size(); i++) {
            Task task = tasks.get(i);
            if (!task.hasClientId(client.getId())) {
                continue;
            }
            hasAssignedTask = true;
            response.append("      ")
                    .append(i + 1)
                    .append(".")
                    .append(task.getStatus())
                    .append("\n");
        }
        if (!hasAssignedTask) {
            response.append("      None\n");
        }
        return response.append(HORIZONTAL_LINE).toString();
    }

    /**
     * Returns clients matching a name search.
     *
     * @param clients Matching clients.
     * @return Formatted search response.
     */
    public String getMatchingClientsMessage(List<Client> clients) {
        if (clients.isEmpty()) {
            return HORIZONTAL_LINE
                    + "    There are no matching clients.\n"
                    + HORIZONTAL_LINE;
        }
        return getClientCollectionMessage("    Matching clients:\n\n", clients);
    }

    /**
     * Returns the response after associating a client with tasks.
     *
     * @param client Associated client.
     * @param tasks Complete task list.
     * @param taskIndexes Associated zero-based task indexes.
     * @return Formatted association response.
     */
    public String getClientAssociatedMessage(Client client, TaskList tasks,
            List<Integer> taskIndexes) {
        StringBuilder response = new StringBuilder(HORIZONTAL_LINE)
                .append("    Client ")
                .append(client.getId())
                .append(" was associated with:\n");
        for (int taskIndex : taskIndexes) {
            response.append("      ")
                    .append(taskIndex + 1)
                    .append(".")
                    .append(tasks.get(taskIndex).getStatus())
                    .append("\n");
        }
        return response.append(HORIZONTAL_LINE).toString();
    }

    /**
     * Returns the response after dissociating a client from tasks.
     *
     * @param client Dissociated client.
     * @param taskIndexes Dissociated zero-based task indexes.
     * @return Formatted dissociation response.
     */
    public String getClientDissociatedMessage(Client client, List<Integer> taskIndexes) {
        String taskNumbers = taskIndexes.stream()
                .map(taskIndex -> Integer.toString(taskIndex + 1))
                .collect(java.util.stream.Collectors.joining(", "));
        String noun = taskIndexes.size() == 1 ? "task " : "tasks ";
        return HORIZONTAL_LINE
                + "    Client " + client.getId() + " was dissociated from "
                + noun + taskNumbers + ".\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the warning shown before a client is deleted.
     *
     * @param client Client awaiting deletion.
     * @param assignedTaskCount Number of assigned tasks.
     * @return Deletion-warning response.
     */
    public String getClientDeleteWarningMessage(Client client, int assignedTaskCount) {
        String taskNoun = assignedTaskCount == 1 ? "task" : "tasks";
        return HORIZONTAL_LINE
                + "    Warning: Deleting client " + client.getId()
                + " (" + client.getFullName() + ") is permanent.\n"
                + "    The client is currently assigned to " + assignedTaskCount
                + " " + taskNoun + ".\n"
                + "    Those tasks will be kept and annotated.\n\n"
                + "    Type `client delete " + client.getId()
                + " confirm` to continue.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns the response after a client is deleted.
     *
     * @param client Deleted client.
     * @param affectedTaskCount Number of affected tasks.
     * @return Client-deleted response.
     */
    public String getClientDeletedMessage(Client client, int affectedTaskCount) {
        String taskNoun = affectedTaskCount == 1 ? "task" : "tasks";
        return HORIZONTAL_LINE
                + "    Client deleted:\n"
                + "      " + client.getId() + " " + client.getFullName() + "\n\n"
                + "    Removed the client from " + affectedTaskCount
                + " " + taskNoun + ".\n"
                + "    The affected tasks were kept and annotated.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns a general saving-error response for multi-file changes.
     *
     * @return Formatted saving-error response.
     */
    public String getSavingChangesErrorMessage() {
        return HORIZONTAL_LINE
                + "     I could not save your changes.\n"
                + "     Please check the data folder and try again.\n"
                + HORIZONTAL_LINE;
    }

    /**
     * Returns a response for corrupted client data.
     *
     * @param message Description of the corrupted data.
     * @return Formatted corrupted-client-data response.
     */
    public String getCorruptedClientDataErrorMessage(String message) {
        return HORIZONTAL_LINE
                + "     The saved client data is corrupted.\n"
                + "     " + message + "\n"
                + HORIZONTAL_LINE;
    }

    private String getClientCollectionMessage(String heading, List<Client> clients) {
        StringBuilder response = new StringBuilder(HORIZONTAL_LINE).append(heading);
        for (Client client : clients) {
            response.append("    ").append(client.getId()).append("\n");
            appendClientDetails(response, client, "      ", false);
            response.append("\n");
        }
        response.append("    Total: ")
                .append(clients.size())
                .append(clients.size() == 1 ? " client.\n" : " clients.\n");
        return response.append(HORIZONTAL_LINE).toString();
    }

    private void appendClientDetails(StringBuilder response, Client client, String indent) {
        appendClientDetails(response, client, indent, true);
    }

    private void appendClientDetails(StringBuilder response, Client client,
            String indent, boolean includeId) {
        if (includeId) {
            response.append(indent).append("ID: ").append(client.getId()).append("\n");
        }
        response.append(indent).append("Name: ").append(client.getFullName()).append("\n")
                .append(indent).append("Phone: ").append(displayValue(client.getPhone())).append("\n")
                .append(indent).append("Email: ").append(displayValue(client.getEmail())).append("\n")
                .append(indent).append("Address: ").append(displayValue(client.getAddress())).append("\n")
                .append(indent).append("Company: ").append(displayValue(client.getCompany())).append("\n")
                .append(indent).append("Notes: ")
                .append(displayMultilineValue(client.getNotes(), indent + "       "))
                .append("\n")
                .append(indent).append("Preferred contact: ")
                .append(client.getPreferredContactMethod() == null
                        ? "-"
                        : client.getPreferredContactMethod().getValue())
                .append("\n");
    }

    private String displayValue(String value) {
        return value.isEmpty() ? "-" : value;
    }

    private String displayMultilineValue(String value, String continuationIndent) {
        return displayValue(value).replace("\n", "\n" + continuationIndent);
    }

    private void appendTaskMetadata(StringBuilder response, Task task, String indent) {
        if (!task.getClientIds().isEmpty()) {
            response.append(indent)
                    .append("Clients: ")
                    .append(String.join(", ", task.getClientIds()))
                    .append("\n");
        }
        for (String note : task.getFormerClientNotes()) {
            response.append(indent).append("Note: ").append(note).append("\n");
        }
    }
}
