import java.util.Scanner;
public class Verity {
	public static final String horizLine = "____________________________________________________________\n";

	public static void main(String[] args) {
		Scanner scanner = new Scanner(System.in);

		String greeting = getGreeting();
		System.out.println(greeting);

		Task[] tasks = new Task[100];
		int taskCount = 0;

		String command = scanner.nextLine();
		while (!command.equals("bye")) {
			String[] commandParts = command.split(" ");
			if (commandParts[0].equals("mark")) {
				int taskNumber = Integer.parseInt(commandParts[1]) - 1;
				tasks[taskNumber].markAsDone();
				System.out.println(horizLine);
				System.out.println("Nice! I've marked this task as done:\n");
				System.out.println(tasks[taskNumber].getStatus() + "\n" + horizLine);
			} else if (commandParts[0].equals("unmark")) {
				int taskNumber = Integer.parseInt(commandParts[1]) - 1;
				tasks[taskNumber].markAsUndone();
				System.out.println(horizLine);
				System.out.println("Ok, I've marked this task as not done yet:\n");
				System.out.println(tasks[taskNumber].getStatus() + "\n" + horizLine);

			 } else if (commandParts[0].equals("list")) {
				System.out.println(horizLine);
				System.out.println("    Here are the tasks in your list:\n");
				for (int i = 0; i < taskCount; ++i) {
					System.out.println("    " + (i + 1) + ": " + tasks[i].getStatus());
				}
				System.out.println(horizLine);
			} else {
				String echo = horizLine
						+ "     added: " + command + "\n"
						+ horizLine;
				System.out.println(echo);
				Task task = new Task(command);
				tasks[taskCount] = task;
				taskCount++;
			}
			command = scanner.nextLine();
		}
		String exitStr = getExitString();
		System.out.println(exitStr);
	}

	private static String getGreeting() {
		// This ASCII art for VERITY was generated by Codex Luna High.
		String banner = "V   V  EEEEE  RRRR   IIIII  TTTTT  Y   Y\n"
				+ "V   V  E      R   R    I      T     Y Y\n"
				+ " V V   EEEE   RRRR     I      T      Y\n"
				+ "  V    E      R R      I      T      Y\n"
				+ "  V    EEEEE  R  RR  IIIII    T      Y";
		return horizLine
				+ banner + "\n\n"
				+ "Hello! I'm Verity.\n"
				+ "I speak only the truth.\n"
				+ "What can I do for you?\n"
				+ horizLine;
	}

	private static String getExitString() {
		return "____________________________________________________________\n"
				+ "    Bye. Hope to see you again soon!\n"
				+ "____________________________________________________________\n";
	}
}
